[package]
name = "twopc-mpc"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
crypto-bigint = { git = "https://github.com/RustCrypto/crypto-bigint.git", features = ["rand_core", "serde"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
subtle = "2.5"
subtle-ng = "2.5"
thiserror = "1.0.47"
k256 = { version = "0.13.1", features = ["arithmetic", "critical-section", "precomputed-tables", "serde"], default-features = false }
merlin = { version = "3.0.0", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
tiresias = { git = "https://github.com/odsy-network/tiresias.git" }
bulletproofs = "4.0.0"
curve25519-dalek = { package = "curve25519-dalek-ng", version = "4", default-features = false, features = ["u64_backend", "serde"] }

# For benchmarking
criterion = { version = "0.5", features = ["html_reports"], optional = true }
rand_core = { version = "0.6.4", features = ["std"], optional = true }
rstest = { version = "0.18.2", optional = true }
rayon = { version = "1.7.0", optional = true }

[dev-dependencies]
rstest = "0.18.2"
rand_core = { version = "0.6.4", features = ["std"] }

[features]
# This feature is for internal-use only (for benchmarking) and exists due to limitations of benchmarking non-public functions in Rust.
# There will be no SemVer support for this feature.
benchmarking = ["dep:criterion", "dep:rand_core", "dep:rstest"]

[[bench]]
name = "benches"
harness = false

[patch.crates-io]
crypto-bigint = { git = "https://github.com/RustCrypto/crypto-bigint.git" }
