[package]
name = "twopc-mpc"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
crypto-bigint = { git = "https://github.com/RustCrypto/crypto-bigint.git", features = ["rand_core", "serde"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
subtle = "2.5"
thiserror = "1.0.47"
merlin = { version = "3.0.0", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

[dev-dependencies]
rstest = "0.17.0"
rand = "0.8.5"
